---
- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: false
  vars:
    provider:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: 8443
      validate_certs: false

  tasks:
    - name: Save the running configuration
      bigip_config:
        save: yes
        provider: "{{ provider }}"

    - name: Upload absolute image to the BIG-IP
      bigip_software_image:
        image: BIGIP-15.1.0.4-0.0.6.iso
        provider: "{{ provider }}"
      tags:
        - upload_bigip

    - name: Installs the BIG-IP OS
      bigip_software_install:
        image: BIGIP-15.1.0.4-0.0.6.iso
        volume: HD1.2
        state: installed
        provider: "{{ provider }}"
      tags:
        - install_bigip

    - name: Verify the system was installed
      bigip_device_info:
        gather_subset: 
          - software-volumes
        provider: "{{ provider }}"
      register: bigip_software_install
      tags:
        - verify

    - name: Displays the device info
      debug:
        var: bigip_software_install
      tags:
        - verify

